# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='product_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arts_app.ProductOrder', to_field='order_id', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order_id',
            field=models.IntegerField(unique=True, verbose_name='订单号'),
        ),
    ]
