# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0003_auto_20180630_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='pay_type',
            field=models.IntegerField(choices=[(0, '货到付款'), (1, '微信支付'), (2, '支付宝支付')], default=0, verbose_name='控制字段'),
        ),
    ]
