# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0004_productorder_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='create_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
