# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arts_app', '0005_chapter_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-a_createtime'], 'verbose_name': '小说', 'verbose_name_plural': '小说'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': '小说章节', 'verbose_name_plural': '小说章节'},
        ),
        migrations.AddField(
            model_name='art',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
